version: '3.9'
services:
  api:
    build: ./api
    container_name: api
    environment:
      - API_UNMS_TOKEN=${API_UNMS_TOKEN}
      - VERSION=${VERSION}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
    volumes:
      - ./api:/app
    links:
      - database
      - redis
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
  client:
    build: ./client
    container_name: client
  database:
    image: postgres:14.1
    restart: always
    container_name: database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redislabs/rejson:latest
    restart: always
    container_name: redis
    volumes:
      - redisdata:/var/lib/redis
    ports:
      - "6379:6379"
  proxy:
    image: nginx:1.21
    restart: always
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    links:
      - database
      - api
      - client
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  pgdata:
  redisdata:
