version: '3.9'
services:
  api:
    build: ./api
    container_name: api
    restart: always
    environment:
      - API_UNMS_TOKEN=${API_UNMS_TOKEN}
      - VERSION=${VERSION}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
    volumes:
      - ./api:/app
    depends_on:
      - database
      - redis
  client:
    build: ./client
    container_name: client
    restart: always
    depends_on:
      - api
  logger:
    container_name: logger
    restart: always
    build: ./workers/logs
    expose:
      - "514"
    ports:
      - "514:514/udp"
    depends_on:
      - server
    volumes:
      - ./workers/logs:/app
  server:
    container_name: server
    restart: always
    build: ./workers/server
    expose:
      - "6969"
    ports:
      - "6969:6969"
    volumes:
      - ./workers/server:/app
  database:
    image: postgres:14.1
    restart: always
    container_name: database
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redislabs/rejson:latest
    restart: always
    container_name: redis
    volumes:
      - redisdata:/var/lib/redis
    ports:
      - "6379:6379"
  proxy:
    image: nginx:1.21
    restart: always
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - worker
      - database
      - server
      - api
      - client
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
volumes:
  pgdata:
  redisdata:
