version: '1.0'
services:
  api:
    build: ./api
    container_name: api
    dns:
      - 10.59.50.20
      - 10.59.50.10
    dns_search: chalons.univ-reims.fr
    depends_on:
      - database
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    network_mode: host
  client:
    build: ./client
    container_name: client
    dns:
      - 10.59.50.20
      - 10.59.50.10
    dns_search: chalons.univ-reims.fr
    ports:
      - 5000
    volumes:
      - ./client:/app
    environment:
      - FLASK_ENV=production
    command: gunicorn --bind=0.0.0.0:5000 src.main:app
    network_mode: host
  database:
    image: postgres
    restart: always
    container_name: database
    dns:
      - 10.59.50.20
      - 10.59.50.10
    dns_search: chalons.univ-reims.fr
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=ac-admin
      - POSTGRES_PASSWORD=ac-pass
      - POSTGRES_DB=ac-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: host
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - client
volumes:
  pgdata:
