#MAIN INFO
version: 1.0

#API
api_token: a60d1c57-576e-43ba-b05f-ec116ec20e85

#OLTs
id_ubiquiti: c4a201ea-ffba-4c25-8d71-161c06917464

#DB ACCESS
DB_NAME: ac-db
DB_USER: ac-admin
DB_PASSWORD: ac-pass
DB_HOST: 10.59.125.10
